version: '3.8'
services:
  db:
    build: ./db
    ports:
      - 8001:8001
    container_name: db
    volumes:
      - ./db/std_table.sql:/docker-entrypoint-initdb.d/std_table.sql


  frontend:
    depends_on:
      - db
    build: ./front
    ports:
      - 8080:80

